#!/bin/bash
set -euo pipefail

# ---------------------------------------------------------------------------
# OpenClaw quick-install script
# Usage:
#   ./run.sh --destination <path> [--port <gateway_port>] [--port-ws <ws_port>]
#            [--password <gateway_password>]
#            [--model-provider <provider>] [--model-base-url <url>]
#            [--model-api-key <key>] [--model-api-adapter <adapter>]
#            [--model-id <model_id>]
#            [--telegram-bot-token <token>]
# ---------------------------------------------------------------------------

DESTINATION=""
PORT="18789"
PORT_WS="18790"
PASSWORD=""
MODEL_PROVIDER="openai"
MODEL_BASE_URL="https://api.openai.com"
MODEL_API_KEY="sk-XXX"
MODEL_API_ADAPTER="openai-completions"
MODEL_ID="gpt-5.4"
TELEGRAM_BOT_TOKEN="XXX:XXX"

while [[ $# -gt 0 ]]; do
  case $1 in
    --destination)
      DESTINATION="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --port-ws)
      PORT_WS="$2"
      shift 2
      ;;
    --password)
      PASSWORD="$2"
      shift 2
      ;;
    --model-provider)
      MODEL_PROVIDER="$2"
      shift 2
      ;;
    --model-base-url)
      MODEL_BASE_URL="$2"
      shift 2
      ;;
    --model-api-key)
      MODEL_API_KEY="$2"
      shift 2
      ;;
    --model-api-adapter)
      MODEL_API_ADAPTER="$2"
      shift 2
      ;;
    --model-id)
      MODEL_ID="$2"
      shift 2
      ;;
    --telegram-bot-token)
      TELEGRAM_BOT_TOKEN="$2"
      shift 2
      ;;
    *)
      echo "Error: Unknown option: $1" >&2
      echo "Usage: $0 --destination <path> [--port <gateway_port>] [--port-ws <ws_port>]" >&2
      echo "          [--password <gateway_password>]" >&2
      echo "          [--model-provider <provider>] [--model-base-url <url>]" >&2
      echo "          [--model-api-key <key>] [--model-api-adapter <adapter>] [--model-id <model_id>]" >&2
      echo "          [--telegram-bot-token <token>]" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$DESTINATION" ]]; then
  echo "Error: --destination is required" >&2
  echo "Usage: $0 --destination <path> [--port <gateway_port>] [--port-ws <ws_port>]" >&2
  echo "          [--password <gateway_password>]" >&2
  echo "          [--model-provider <provider>] [--model-base-url <url>]" >&2
  echo "          [--model-api-key <key>] [--model-api-adapter <adapter>] [--model-id <model_id>]" >&2
  echo "          [--telegram-bot-token <token>]" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Clone repository
# ---------------------------------------------------------------------------
git clone --depth=1 https://github.com/minhng92/openclaw-minimal-docker-compose "$DESTINATION"
rm -rf "$DESTINATION/.git"
rm -f "$DESTINATION/LICENSE" "$DESTINATION/README.MD" "$DESTINATION/run.sh"
rm -rf "$DESTINATION/screenshots"

# Change ownership / permissions
sudo chown -R "$USER:$USER" "$DESTINATION"
find "$DESTINATION" -type f -exec chmod 644 {} \;
find "$DESTINATION" -type d -exec chmod 755 {} \;

# ---------------------------------------------------------------------------
# Helper: portable sed (Linux vs macOS)
# ---------------------------------------------------------------------------
escape_sed_replacement() {
  printf '%s' "$1" | sed -e 's/[\\/&]/\\&/g'
}

sed_inplace() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# ---------------------------------------------------------------------------
# Patch docker-compose.yml: exposed ports (only the host-side, before colon)
# ---------------------------------------------------------------------------
COMPOSE_FILE="$DESTINATION/docker-compose.yml"

sed_inplace "s/\"18789:18789\"/\"${PORT}:18789\"/g" "$COMPOSE_FILE"
sed_inplace "s/\"18790:18790\"/\"${PORT_WS}:18790\"/g" "$COMPOSE_FILE"

# ---------------------------------------------------------------------------
# Write agent.env
# ---------------------------------------------------------------------------
AGENT_ENV="$DESTINATION/agent.env"

{
  echo "# agent.env – generated by run.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo ""
  echo "# -----------------------------------------------------------------------------"
  echo "# Gateway auth"
  echo "# -----------------------------------------------------------------------------"
  if [[ -n "$PASSWORD" ]]; then
    echo "OPENCLAW_GATEWAY_PASSWORD=$(printf '%q' "$PASSWORD")"
  else
    echo "# OPENCLAW_GATEWAY_PASSWORD=minhng.info"
  fi
  echo ""
  echo "# -----------------------------------------------------------------------------"
  echo "# Model provider"
  echo "# -----------------------------------------------------------------------------"
  if [[ -n "$MODEL_API_KEY" ]]; then
    echo "MODEL_PROVIDER=\"$MODEL_PROVIDER\""
    echo "MODEL_PROVIDER_BASE_URL=\"$MODEL_BASE_URL\""
    echo "MODEL_PROVIDER_API_KEY=\"$MODEL_API_KEY\""
    echo "MODEL_PROVIDER_API_ADAPTER=\"$MODEL_API_ADAPTER\"   # openai-completions | openai-responses | anthropic-messages | google-generative-ai"
    echo "MODEL_PROVIDER_MODEL_ID=\"$MODEL_ID\""
  else
    echo "# MODEL_PROVIDER=\"openai\""
    echo "# MODEL_PROVIDER_BASE_URL=\"https://api.openai.com\""
    echo "# MODEL_PROVIDER_API_KEY=\"sk-XXX\""
    echo "# MODEL_PROVIDER_API_ADAPTER=\"openai-completions\"   # openai-completions | openai-responses | anthropic-messages | google-generative-ai"
    echo "# MODEL_PROVIDER_MODEL_ID=\"gpt-5.4\""
  fi
  echo ""
  echo "# -----------------------------------------------------------------------------"
  echo "# Channels"
  echo "# -----------------------------------------------------------------------------"
  if [[ -n "$TELEGRAM_BOT_TOKEN" ]]; then
    echo "TELEGRAM_BOT_TOKEN=\"$TELEGRAM_BOT_TOKEN\"   # https://docs.openclaw.ai/channels/telegram"
  else
    echo "# TELEGRAM_BOT_TOKEN=\"XXX:XXX\"   # https://docs.openclaw.ai/channels/telegram"
  fi
} > "$AGENT_ENV"

chmod 600 "$AGENT_ENV"

# ---------------------------------------------------------------------------
# Run docker compose
# ---------------------------------------------------------------------------
DOCKER_SUDO=""
if ! docker ps >/dev/null 2>&1; then
  echo "Docker requires sudo privileges"
  DOCKER_SUDO="sudo"
fi

if ! is_present="$(type -p "docker-compose")" || [[ -z $is_present ]]; then
  $DOCKER_SUDO docker compose -f "$COMPOSE_FILE" up -d
else
  $DOCKER_SUDO docker-compose -f "$COMPOSE_FILE" up -d
fi

echo ""
echo "✅ OpenClaw started!"
echo "   Gateway  : http://localhost:${PORT}"
echo "   WebSocket: http://localhost:${PORT_WS}"
if [[ -n "$PASSWORD" ]]; then
  echo "   Password : $PASSWORD"
else
  echo "   Password : minhng.info (default – set --password to override)"
fi
echo ""
echo "   agent.env written to: $AGENT_ENV"
